dataset_name: Office-Home
domain_names:
  - Art
  - Clipart
  - Product
  - Real World
k_fold:
  - 0
  - 1
  - 2
type_calibrate: in_domain
path_save: /vinbrain/anhng/domain_adaptation/experiments_new/
