dataset_name: 
  - Office
domain_name:
  - amazon
kfold_exp:
  - 0
path_data: /workspace/raid/tientran/
path_save: /vinbrain/tientran/feedbackloop/Calibrate_temp/research/domain_calibration/experiments/