dataset_name: 
  - Domain-net
kfold_exp:
  - 0
- type_loss: entropy
- type_ece: origin
path_data: /workspace/raid/tientran/
path_save: /vinbrain/tientran/feedbackloop/Calibrate_temp/research/domain_calibration/experiments/