dataset_name: 
  - Office-Home
kfold_exp:
  - 0
type_loss: entropy
type_ece: origin
path_data: /workspace/raid/anhng/domain-adaptation/
path_save: /workspace/vinbrain/anhng/domain_adaptation/experiments_new/