dataset_name: 
  - Office
kfold_exp:
  - 0
  - 1
  - 2
type_losses:
  - entropy
  - both
type_ece: origin
type_calibrate: in_domain
path_data: /workspace/raid/anhng/domain-adaptation/
path_save: /workspace/vinbrain/anhng/domain_adaptation/experiments_new/
