dataset_name: 
  - Office
kfold_exp:
  - 0
  - 1
  - 2
image_size_ratio: 256
input_size: 224
batch_size: 132
num_workers: 4
path_data: /workspace/raid/anhng/domain-adaptation/
path_weight: /workspace/vinbrain/anhng/domain_adaptation/experiments_new/
path_style_transfer: /workspace/vinbrain/anhng/domain_adaptation/experiments_style_transfer/
train_augment:
  - CenterCrop
  - Normalize
val_augment:
  - CenterCrop
  - Normalize
