dataset_name: 
  - Office-Home
domain_name:
  - Art
kfold_exp:
  - 0
image_size_ratio: 256
input_size: 224
batch_size: 132
num_workers: 4
learning_rate_init: 1e-7
learning_rate_optimize: 1.52e-03
number_epochs: 50
patience: 7
path_data: /workspace/raid/tientran/
path_save: /vinbrain/tientran/feedbackloop/Calibrate_temp/research/domain_calibration/experiments/
get_learning_rate: False
train_augment:
  - CenterCrop
  - Normalize
val_augment:
  - CenterCrop
  - Normalize
