dataset_name: 
  - Office-Home
domain_name:
  - Real World
kfold_exp:
  - 0
image_size_ratio: 256
input_size: 224
batch_size: 132
num_workers: 4
learning_rate_init: 1e-7
learning_rate_optimize: 1.52e-03
number_epochs: 50
patience: 7
path_data: /workspace/raid/anhng/domain-adaptation/
path_save: /workspace/vinbrain/anhng/domain_adaptation/experiments_new/
get_learning_rate: False
train_augment:
  - CenterCrop
  - Flip
  - Blur
  - GaussNoise
  - RandomBrightness
  - Normalize
val_augment:
  - CenterCrop
  - Normalize
